### ISSUE TITLE
Module build failed: RTCodeError: Document should have a root element

### ISSUE THREAD

**Issue by dennis-b** [AlexanderPavlenko/react-templates-loader#2]
hi,

when i try to use this loader i get :

"Module build failed: RTCodeError: Document should have a root element"
I tested on template: `<div></div>`

when i use gulp-react-templates it compiles ok

**Comment by AlexanderPavlenko** [comment]
https://github.com/wix/react-templates/blob/1e32a7c22249ffb4c0a251648ae4cffb95e8adbf/src/reactTemplates.js#L472
Maybe that's not the loader's issue. What about non-blank tags like `<div>&nbsp;</div>`?

**Comment by dennis-b** [comment]
thank you for fast response.

for `<div>&nbsp;</div>` i get the same error (for any template i get this error).

p.s
if the problem in react-templates, so in strange way the gulp-react-templates plugin do the work .

**Comment by AlexanderPavlenko** [comment]
Well, I'm not using this loader currently, and not sure what causes this problem.
Let's ask @liady, as a contributor he may have some hints.

**Comment by liady** [comment]
Hey,
It seems to work when I try it with my configuration.
I set up a minimal demo repository with an empty div - can you try running it and see if it reproduces?
Let me know if your webpack config is different, so I could test it.

https://github.com/liady/react-templates-loader-test

**Comment by dennis-b** [comment]
hey

in the test you are doing : `import emptyTemplate from "./Empty.rt";`

according the documentation you suppose to do : `require("react-templates!./template.rt");`

you are write when i remove  `react-templates!` it works fine .

10X

p.s
when i add  `react-templates!` i get the same error

**Comment by liady** [comment]
ok, so that was probably the problem.
Adding `react-templates` as a loader in the `webpack.config.js`, and also piping it manually in the `require("react-templates!./template.rt");`, actually runs it **twice** on the template file, causing an error.

It is sufficient to only add it as a loader in the config file, or adding it manually in the require, but not both.

@AlexanderPavlenko, I think we can close this issue. Added PR #3 in order to add note to the README
